### ISSUE TITLE
How to test a Camel route using Quarkus?

### ISSUE THREAD

**Issue by hakuseki** [citrusframework/citrus#1113]
**Citrus Version**
4.1.0

**Question**
How to test a Camel route using Quarkus?

**What I've tried so far**
The Quarkus Insight #149 was a really good presentation on how to unit test Quarkus using Citrus.
There's also support for Camel in Citrus but how does that work in Quarkus?

Are there any resources out there that can show a basic test class using JUnit in Quarkus with a Camel route?

I have tried to puzzle the documentation together for a test but I fail.

To me, it seems that Citrus works fine when using Camel in Spring or plain Quarkus but when combined something is missing and I don't know what…

My test class:

```Java
@QuarkusTest
@CitrusSupport
public class CamelRoute2Test extends CamelQuarkusTestSupport {
    @CitrusResource
    TestCaseRunner t;

    @Inject
    CamelContext camelContext;

    @Test
    @CitrusTest
    @DisplayName("Citrus Test")
    void citrusTest() {
        t.when(send(camel(camelContext).endpoint(direct("hello")::getUri))
                   .message()
                   .type(MessageType.PLAINTEXT)
                   .body("Hello"));

        t.then(receive(camel(camelContext).endpoint(seda("greetings")::getUri))
                   .message()
                   .type(MessageType.PLAINTEXT)
                   .body("Hello from Citrus!"));
    }
}
```

I have tried different approaches but it fails and I have exhausted my options, it seems:

```
2024-01-22 10:58:02,469 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) ********************************************************************************
2024-01-22 10:58:02,470 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) Testing: citrusTest() (dts.route.CamelRoute2Test)
2024-01-22 10:58:02,470 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) ********************************************************************************
2024-01-22 10:58:02,470 WARN  [org.apa.cam.qua.tes.CamelQuarkusTestSupport] (main) Test with `true` in `isUserRouteBuilder' and `RouteBuilder` detected in the context registry. All tests will share this routeBuilder from the registry. This is usually not intended. If `@Produces` is used to create such a RouteBuilder, please refactor the code by overriding the method `createRouteBuilder()` instead.
2024-01-22 10:58:02,768 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) ********************************************************************************
2024-01-22 10:58:02,768 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) Testing: citrusTest() (dts.route.CamelRoute2Test)
2024-01-22 10:58:02,768 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) ********************************************************************************
2024-01-22 10:58:02,769 WARN  [org.apa.cam.qua.tes.CamelQuarkusTestSupport] (main) Test with `true` in `isUserRouteBuilder' and `RouteBuilder` detected in the context registry. All tests will share this routeBuilder from the registry. This is usually not intended. If `@Produces` is used to create such a RouteBuilder, please refactor the code by overriding the method `createRouteBuilder()` instead.
2024-01-22 10:58:02,814 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) ********************************************************************************
2024-01-22 10:58:02,815 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) Testing done: citrusTest() (dts.route.CamelRoute2Test)
2024-01-22 10:58:02,815 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) Took: 44ms (44 millis)
2024-01-22 10:58:02,815 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) ********************************************************************************
WARNING: A Java agent has been loaded dynamically (/Users/oyn177/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.4/byte-buddy-agent-1.14.4.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
2024-01-22 10:58:03,656 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) ********************************************************************************
2024-01-22 10:58:03,657 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) Testing done: citrusTest() (dts.route.CamelRoute2Test)
2024-01-22 10:58:03,657 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) Took: 886ms (886 millis)
2024-01-22 10:58:03,657 INFO  [org.apa.cam.tes.jun.CamelTestSupport] (main) ********************************************************************************

org.citrusframework.exceptions.TestCaseFailedException: Sending message to camel endpoint resulted in exception

	at org.citrusframework.DefaultTestCase.executeAction(DefaultTestCase.java:146)
	at org.citrusframework.DefaultTestCaseRunner.run(DefaultTestCaseRunner.java:129)
	at org.citrusframework.GherkinTestActionRunner.when(GherkinTestActionRunner.java:46)
	at dts.route.CamelRoute2Test.citrusTest(CamelRoute2Test.java:67)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.citrusframework.exceptions.CitrusRuntimeException: Sending message to camel endpoint resulted in exception
	at org.citrusframework.camel.endpoint.CamelProducer.send(CamelProducer.java:82)
	at org.citrusframework.actions.SendMessageAction.doExecute(SendMessageAction.java:175)
	at org.citrusframework.actions.AbstractTestAction.execute(AbstractTestAction.java:59)
	at org.citrusframework.DefaultTestCase.executeAction(DefaultTestCase.java:139)
	... 8 more
Caused by: java.util.concurrent.RejectedExecutionException: CamelContext is stopped
	at org.apache.camel.support.cache.DefaultProducerCache.send(DefaultProducerCache.java:157)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:176)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:172)
	at org.apache.camel.impl.engine.DefaultProducerTemplate.send(DefaultProducerTemplate.java:137)
	at org.citrusframework.camel.endpoint.CamelProducer.send(CamelProducer.java:77)
	... 11 more
```

My route to test

```Java
from(direct("hello"))
            .routeId("helloRoute")
            .to("log:com.consol.citrus.camel?level=INFO")
            .to(seda("greetings"));

from(seda("greetings"))
            .setBody(simple("Hello from Citrus!"));
```

Using Quarkus 3.6.5 and Citrus 4.1.0

Please advise, thanks

M

**Additional information**

Posted in Quarkus as well: https://github.com/quarkusio/quarkus/discussions/38328

@christophd

**Comment by christophd** [comment]
This is because Citrus will create its own CamelContext and uses it to send the message. Since this Citrus related CamelContext has not been started yet the test runs into the error CamelContext is stopped.

We need to make Citrus aware of the CamelContext that is injected by Quarkus.

In order to do this you can add org.citrusframework.spi.BindToRegistry annotation to the injected CamelContext. Citrus support will then also use this injected CamelContext for its own purpose.

This should be working:

@QuarkusTest
@CitrusSupport
public class CamelRoute2Test extends CamelQuarkusTestSupport {
    @CitrusResource
    TestCaseRunner t;

    @Inject
    @BindToRegistry
    CamelContext camelContext;

    @Test
    @DisplayName("Citrus Test")
    void citrusTest() {
        t.when(send(camel(camelContext).endpoint(direct("hello")::getUri))
                   .message()
                   .type(MessageType.PLAINTEXT)
                   .body("Hello"));

        t.then(receive(camel(camelContext).endpoint(seda("greetings")::getUri))
                   .message()
                   .type(MessageType.PLAINTEXT)
                   .body("Hello from Citrus!"));
    }
}
Please be careful to reference the annotation in org.citrusframework.spi.BindToRegistry because Camel itself also provides a BindToRegistry annotation. We need to use the one provided by Citrus.

Please let me know if this is working for you.

**Comment by christophd** [comment]
I think the 'seda' component is not able to broadcast the message to multiple consumers. By the time Citrus adds the consumer the message has already been consumed by the 2nd Camel route itself. I believe in 'seda' it is first consumer wins the others do not get the message.

With `direct` it fails as soon as more than one single consumer connect to the endpoint.

I suppose to change your sample route to something like this:

```java
from("direct:hello")
        .routeId("helloRoute")
        .setBody(simple("User said: ${body}"))
        .to("log:org.citrusframework.camel?level=INFO")
        .to("seda:greetings");
```

So you have a single route and Citrus consumes as a single consumer from the `seda` endpoint. This is how I got it working on my side.

**Comment by hakuseki** [comment]
Yes that made the test green. 
However it is a little confusing receiving on a route which has not from()…

```java
from(direct("hello"))
            .routeId("helloRoute")
            .setBody(simple("Hello from Citrus!"))
            .to(seda("greetings"));
```

```java
@QuarkusTest
@CitrusSupport
public class CamelRoute2Test extends CamelQuarkusTestSupport {
    @CitrusResource
    TestCaseRunner t;

    @Inject
    @BindToRegistry
    CamelContext camelContext;

    /**
     * Is use route builder boolean.
     *
     * @return the boolean
     */
    @Override
    public boolean isUseRouteBuilder() {
        return false;
    }

    @Test
    @DisplayName("Citrus Test")
    void citrusTest() {
        t.when(send(camel(camelContext).endpoint(direct("hello")::getUri))
                   .message()
                   .type(MessageType.PLAINTEXT)
                   .body("Hello"));

        t.then(receive(camel(camelContext).endpoint(seda("greetings")::getUri))
                   .message()
                   .type(MessageType.PLAINTEXT)
                   .body("Hello from Citrus!"));
    }
```

**Comment by christophd** [comment]
Sorry to see you confused. But I think this is how the test should work where the Camel route is the producer of data and Citrus is the consumer to verify the outcome of the route. So the only thing is that Citrus doe not use a `from()` but usees the `receive()` action to consume the data.

I think it makes sense

**Comment by hakuseki** [comment]
OK, sorry if I appear to be slow thinker but I still can't figure this out.

We are trying to build our routes to only do one thing, let's say transformation.
My route direct("transformation") receives an XML and it will return a marshalled JSON.
We do not chain our routes, we have one starting route and then they all get called in sequence

from(quartz("start))
 .to(direct("readXML))
 .to(direct("transform")
 .to(direct("sendJSON")

So my question is, how to test a single route?

**Comment by christophd** [comment]
no worries, you ain't no slow thinker!

So for me an integration test would test the application as a whole with Citrus providing input to the 1st route and verifying the final output (output of `sendJSON` route).

If you also want to test the individual routes in isolation (which is a good idea) I would recommend to use more of a unit test approach with Apache Camel where you are able to invoke a single route and apply some mock component or work with route advice to verify the route results. In the unit test you will not connect to the real messaging transports and rather use the mock component to test the route in complete isolation.

In the integration test you load the whole application (all routes) and connect to real messaging transports and infrastructure. During integration testing it is hard to invoke and verify only a single route in your application as you will have multiple consumers on the direct endpoints which is not allowed in Apache Camel.

Hope that makes sense for you

**Comment by hakuseki** [comment]
Thanks for your input, it makes sense to test everything in integration.

The reason I wanted to use Citrus is for the easy setup and calls, Camel AdviceWith and MockEndpoint doesn't work for me, I have yet seen any working Unit tests for Camel using a production route instead of a local (within unit test) created dummy route.

I'll continue trying…

Danke
